title: seminUSP 
author: lubianat
email: tiago.lubiana.alves@usp.br
description: Agenda dos seminarios que rolam na USP Butanta
# social links
twitter_username: lubianat
github_username:  lubianat

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
